import { test, expect, Page, Route } from '@playwright/test';
import { installApp, STUDIO_NAV, ALL_FEATURES } from './helpers/app';

// ── G13 slice 2 — the in-place canvas TEXT editor (docs/design/G13-INPLACE-
// EDITING.md §2–3) ────────────────────────────────────────────────────────────
// Double-click a stamped text region on the live canvas → edit it in place →
// commit flows through the ONE debounced saveBlocks → PUT /settings. These
// tests drive the REAL page against a stamped preview fixture generated by the
// real renderSiteBlocks (byte-real data-dds-* stamps), intercept PUT /settings,
// and assert the STORED payload: markdown source for md fields, plain text for
// plain fields — never rendered HTML. Escape cancels (no PUT), caps clamp with
// a warning, core sections route to their panel, an unstamped (old-function)
// render feature-detects down to the panel editor, Preview mode never edits.

const META = { blocks: [
  { sid: 'title', key: 'block_title', src_index: 0 },
  { sid: 'richtext', key: 'block_richtext', src_index: 1 },
  { sid: 'cta', key: 'block_cta', src_index: 2 },
], pages: {} };
const BLOCKS = [
  { type: 'title', title: 'Your heading', subtitle: 'A quiet sub line' },
  { type: 'richtext', title: 'Our story', body: 'Hello **world**\n\n- first\n- second' },
  { type: 'cta', text: 'Ready to begin?', button: 'Book now', url: 'https://x.example' },
];
// Generated by the REAL renderSiteBlocks + validateBlocksWithMap over BLOCKS —
// regenerate with scripts in the design doc's test plan if the stamp contract moves.
const SECTIONS =
  '<section id="your-heading" data-dds-sid="title" data-dds-key="block_title" data-dds-src="0" class="block wrap block-titleonly"><h2 data-dds-field="title">Your heading</h2><p class="title-sub" data-dds-field="subtitle">A quiet sub line</p></section>' +
  '<section id="our-story" data-dds-sid="richtext" data-dds-key="block_richtext" data-dds-src="1" class="block wrap block-richtext"><h2 data-dds-field="title">Our story</h2><div class="prose" data-dds-field="body" data-dds-md="1"><p>Hello <strong>world</strong></p>\n<ul><li>first</li><li>second</li></ul></div></section>' +
  '<section id="cta" data-dds-sid="cta" data-dds-key="block_cta" data-dds-src="2" class="block alt block-cta"><div class="wrap cta-inner"><p class="cta-text" data-dds-field="text">Ready to begin?</p><a class="btn" href="https://x.example" rel="noopener" data-dds-field="button">Book now</a></div></section>';
const PAGE_HTML = (sections: string) =>
  '<!doctype html><html><head><meta charset="utf-8"><style>.block{padding:24px}.hero{padding:32px}</style></head><body>' +
  '<main id="main"><section class="hero" data-dds-core="hero"><h1>Marlow’s Kitchen</h1><p>Fresh, local, yours.</p></section>' + sections + '</main></body></html>';
const STRIP = / data-dds-(?:sid|key|field|md|core|src)="[^"]*"/g;

const SETTINGS = { blocks: BLOCKS, section_meta: META };
const API = {
  '/site': { data: { site: { id: 's1', edition: 'presence', status: 'ready', template_slug: 'business-classic', template_version: 1 }, identity: { business_name: 'Marlow’s Kitchen' }, location: {} } },
  '/offerings': { data: [] }, '/faqs': { data: [] }, '/testimonials': { data: [] }, '/posts': { data: [] },
  '/media': { data: [] }, '/health': { data: {} }, '/notes': { data: [] }, '/moments': { data: [] },
  '/changes': { data: { count: 0, first_publish: false, changes: [], blockers: 0, warnings: 0, draft_hash: 'e2e-draft-hash' } },
  '/dev/customization': { data: { theme_tokens: {}, custom_css: '', custom_html: '', allowed_tokens: [], can_edit_css: false, updated_at: null, updated_by: null } },
  '/schedule': { data: { scheduled: [] } },
  '/content-library': { data: [] },
  '/portal/context': { data: {
    site_role: 'business_owner', edition: 'presence', edition_key: 'studio_os', edition_name: 'Studio OS',
    edition_features: ALL_FEATURES, is_agency: false, is_operator: false, sees_full_workspace: true,
    capabilities: ['edit', 'publish', 'invite', 'configure', 'use_developer_mode', 'view_all'],
    landing: '/presence.html', attention_count: 0, nav: STUDIO_NAV, plan_key: 'presence', upsell: null,
  } },
};

type Mounted = { frame: ReturnType<Page['frameLocator']>; puts: Array<Record<string, unknown>> };
async function mountCanvas(page: Page, opts: { html?: string; settings?: Record<string, unknown> } = {}): Promise<Mounted> {
  const settings = opts.settings ?? SETTINGS;
  await installApp(page, { api: { ...API, '/settings': { data: settings } } });
  const puts: Array<Record<string, unknown>> = [];
  // later-registered routes win: capture PUT /settings (echo the body back, the
  // real handler shape) and serve the stamped preview HTML.
  await page.route('**/functions/v1/presence/settings**', (route: Route) => {
    if (route.request().method() === 'PUT') {
      const body = route.request().postDataJSON() as Record<string, unknown>;
      puts.push(body);
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ data: { ...settings, ...body, section_meta: META } }) });
    }
    return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ data: settings }) });
  });
  await page.route('**/functions/v1/presence/preview**', (route: Route) =>
    route.fulfill({ status: 200, contentType: 'text/html; charset=utf-8', body: opts.html ?? PAGE_HTML(SECTIONS) }));
  await page.goto('/presence.html#design');
  const frame = page.frameLocator('#designPreview');
  await expect(frame.locator('#main > section').first()).toBeVisible();
  return { frame, puts };
}

test.describe('G13 in-place canvas text editor', () => {
  test('double-click → edit → Enter commits: ONE debounced PUT carries the new string at the stored path', async ({ page }) => {
    const { frame, puts } = await mountCanvas(page);
    const h2 = frame.locator('section.block-titleonly [data-dds-field="title"]');
    await h2.dblclick();
    // the session: an editable, a11y-labelled textbox with a live announcement
    await expect(h2).toHaveAttribute('contenteditable', /true|plaintext-only/);
    await expect(h2).toHaveAttribute('role', 'textbox');
    await expect(frame.locator('#dds-ipe-live')).toContainText(/Editing/);
    await page.keyboard.press('ControlOrMeta+a');
    await page.keyboard.insertText('A bolder heading');
    await page.keyboard.press('Enter');
    // the canvas reflects the edit immediately (the element holds it) and the
    // session chrome is fully restored
    await expect(h2).toHaveText('A bolder heading');
    await expect(h2).not.toHaveAttribute('contenteditable', /.+/);
    await expect(h2).not.toHaveAttribute('role', /.+/);
    // the debounced save lands as ONE PUT with the string at the right path
    await page.waitForRequest((r) => r.method() === 'PUT' && r.url().includes('/settings'), { timeout: 6000 });
    expect(puts.length).toBe(1);
    const blocks = puts[0].blocks as typeof BLOCKS;
    expect(blocks[0].title).toBe('A bolder heading');
    expect(blocks[0].subtitle).toBe('A quiet sub line');   // siblings untouched
    expect(blocks[1]).toEqual(BLOCKS[1]);                  // other blocks ride whole
  });

  test('Escape cancels: the DOM reverts and NO save fires; click-away with no change also saves nothing', async ({ page }) => {
    const { frame, puts } = await mountCanvas(page);
    const sub = frame.locator('[data-dds-field="subtitle"]');
    await sub.dblclick();
    await expect(sub).toHaveAttribute('contenteditable', /.+/);
    await page.keyboard.press('ControlOrMeta+a');
    await page.keyboard.insertText('junk that must vanish');
    await page.keyboard.press('Escape');
    await expect(sub).toHaveText('A quiet sub line');      // the original DOM is back
    await expect(sub).not.toHaveAttribute('contenteditable', /.+/);
    // an unchanged commit (blur without typing) is a no-op too
    const h2 = frame.locator('section.block-titleonly [data-dds-field="title"]');
    await h2.dblclick();
    await expect(h2).toHaveAttribute('contenteditable', /.+/);
    await frame.locator('section.block-cta').click();      // click away = commit (unchanged)
    await page.waitForTimeout(1800);                       // longer than the 1.2s debounce
    expect(puts.length).toBe(0);
  });

  test('a markdown field round-trips markdown SOURCE — never rendered HTML — and the mini-bar bolds via markdown', async ({ page }) => {
    const { frame, puts } = await mountCanvas(page);
    const prose = frame.locator('[data-dds-field="body"]');
    await prose.dblclick();
    await expect(prose).toHaveAttribute('contenteditable', 'true');
    await expect(frame.locator('#dds-ipe-bar')).toBeVisible();   // md fields get B · I · Link
    await page.keyboard.press('End');
    await page.keyboard.insertText(' plus more');
    await page.keyboard.press('ControlOrMeta+Enter');            // md commit
    await page.waitForRequest((r) => r.method() === 'PUT' && r.url().includes('/settings'), { timeout: 6000 });
    const body = (puts[0].blocks as typeof BLOCKS)[1].body as string;
    expect(body).toContain('**world**');                   // existing markdown survives
    expect(body).toContain('plus more');                   // the edit landed
    expect(body).toContain('- first');                     // the list survives as source
    expect(body).not.toMatch(/<\/?[a-z]/);                 // NEVER HTML into storage
    expect((puts[0].blocks as typeof BLOCKS)[1].title).toBe('Our story');
  });

  test('caps: a plain field clamps at the validator cap (cta text 160) with a visible warning', async ({ page }) => {
    const { frame, puts } = await mountCanvas(page);
    const cta = frame.locator('[data-dds-field="text"]');
    await cta.dblclick();
    await expect(cta).toHaveAttribute('contenteditable', /.+/);
    await page.keyboard.press('ControlOrMeta+a');
    await page.keyboard.insertText('x'.repeat(200));
    await page.keyboard.press('Enter');
    await expect(page.getByText(/Trimmed to the field/)).toBeVisible();
    await page.waitForRequest((r) => r.method() === 'PUT' && r.url().includes('/settings'), { timeout: 6000 });
    expect(((puts[0].blocks as typeof BLOCKS)[2].text as string).length).toBe(160);
  });

  test('core sections are NOT editable this slice — double-click routes to their panel tab', async ({ page }) => {
    const { frame } = await mountCanvas(page);
    await frame.locator('[data-dds-core="hero"]').dblclick();
    await expect(page.locator('#view-business')).toBeVisible();      // hero → the Business tab
    await expect(frame.locator('[contenteditable]')).toHaveCount(0); // nothing became editable
  });

  test('an OLD-function render (no stamps) gets no in-place affordance — the panel editor still works', async ({ page }) => {
    const { frame, puts } = await mountCanvas(page, {
      html: PAGE_HTML(SECTIONS).replace(STRIP, ''),
      settings: { blocks: BLOCKS },   // no section_meta either — the full stale-deploy shape
    });
    await frame.locator('section.block-titleonly h2').dblclick();
    await expect(frame.locator('[contenteditable]')).toHaveCount(0); // feature-detect: no editor
    await expect(page.locator('#settingsPanel')).toHaveClass(/on/);  // …but the panel path still opens
    await page.waitForTimeout(1500);
    expect(puts.length).toBe(0);
  });

  test('Edit mode is the gate: Preview mode never edits in place', async ({ page }) => {
    const { frame, puts } = await mountCanvas(page);
    await page.locator('#dcModeSeg button[data-dcmode="preview"]').click();
    await expect(frame.locator('#main > section').first()).toBeVisible();  // the view-mode repaint landed
    await frame.locator('section.block-titleonly [data-dds-field="title"]').dblclick();
    await page.waitForTimeout(400);
    await expect(frame.locator('[contenteditable]')).toHaveCount(0);
    expect(puts.length).toBe(0);
  });

  test('the hover toolbar keeps working alongside: Duplicate after an in-place commit', async ({ page }) => {
    const { frame, puts } = await mountCanvas(page);
    const h2 = frame.locator('section.block-titleonly [data-dds-field="title"]');
    await h2.dblclick();
    await page.keyboard.press('ControlOrMeta+a');
    await page.keyboard.insertText('Edited first');
    await page.keyboard.press('Enter');
    await page.waitForRequest((r) => r.method() === 'PUT' && r.url().includes('/settings'), { timeout: 6000 });
    expect(puts.length).toBe(1);
    // the canvas reloaded after the save — the toolbar still drives section ops
    await expect(frame.locator('#main > section').first()).toBeVisible();
    await frame.locator('section.block-richtext').hover();
    const dup = frame.locator('#dds-dc-bar button', { hasText: 'Duplicate' });
    await expect(dup).toBeVisible();
    await dup.click();
    await page.waitForRequest((r) => r.method() === 'PUT' && r.url().includes('/settings'), { timeout: 6000 });
    const last = puts[puts.length - 1].blocks as typeof BLOCKS;
    expect(last.length).toBe(4);                            // duplicated in place
    expect(last[0].title).toBe('Edited first');             // the in-place edit persisted through
    expect(last[2].type).toBe('richtext');
  });
});
